import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/home/calluma/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell" });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on("pageerror", (e) => console.log("pageerror", String(e).slice(0, 300)));
await page.goto("http://127.0.0.1:5320/?demo&manuscript=manuscripts/potentiality.md");
await page.waitForFunction(() => document.querySelectorAll(".preview-pages g.typst-page").length > 0, null, { timeout: 60000 });
const line = page.locator(".cm-line", { hasText: "which it occurs" }).first();
await line.click(); await page.keyboard.press("End");
await page.keyboard.type(" See [@badiouEth", { delay: 40 });
await page.waitForTimeout(800);
const lineText = async () => page.evaluate(() => [...document.querySelectorAll(".cm-line")].find((l) => l.textContent.includes("which it occurs"))?.textContent);
console.log("after typing:", await lineText());
console.log("tooltip:", (await page.locator(".cm-tooltip-autocomplete li").allTextContents()).slice(0, 4));
console.log("selected:", await page.locator(".cm-tooltip-autocomplete li[aria-selected]").allTextContents());
await page.screenshot({ path: "out/complete-1.png" });
await page.keyboard.press("Enter");
await page.waitForTimeout(500);
console.log("after Enter:", await lineText());
await page.waitForTimeout(1500);
console.log("after 1.5s:", await lineText());
await browser.close();
