import { chromium } from "playwright";
import { writeFileSync } from "node:fs";
const browser = await chromium.launch({ executablePath: "/home/calluma/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell" });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
await page.goto("http://127.0.0.1:5320/?demo&manuscript=manuscripts/refusing-the-possible.md");
await page.waitForFunction(() => window.writer?.workspace?.getSnapshot().result?.revision >= 2, null, { timeout: 60000 });
await page.waitForTimeout(1000);
const pdf = await page.evaluate(async () => { const r = await window.writer.workspace.exportPdf(); return r.bytes ? Array.from(r.bytes) : r.error; });
writeFileSync("out/rev2.pdf", Buffer.from(pdf));
console.log(JSON.stringify(await page.evaluate(() => { const s = window.writer.workspace.getSnapshot(); return { rev: s.result.revision, resultArtifact: s.result.artifact?.byteLength, snapArtifact: s.artifact?.byteLength, diags: s.result.diagnostics }; }))); console.log("svg pages", await page.evaluate(() => document.querySelectorAll(".preview-pages g.typst-page").length), "artifact bytes", await page.evaluate(() => window.writer.workspace.getSnapshot().artifact?.byteLength));
await browser.close();
