import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/home/calluma/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell" });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
await page.goto("http://127.0.0.1:5320/?demo&manuscript=manuscripts/refusing-the-possible.md");
await page.waitForFunction(() => (window.writer?.workspace?.getSnapshot().result?.order.length ?? 0) === 3 && Number(document.querySelector(".preview-pages")?.dataset.renderedRevision ?? 0) >= 2, null, { timeout: 60000 });
const state = () => page.evaluate(() => ({ rev: window.writer.workspace.getSnapshot().result.revision, shown: document.querySelector(".preview-pages").dataset.renderedRevision, pages: [...document.querySelectorAll("canvas.page")].map((c) => `${c.dataset.page}:v${c.dataset.version ?? "-"}:${c.width}`), eventPage: window.writer.workspace.getSnapshot().result.positions.filter((p) => p.record === "chapters/event.md").map((p) => p.page) }));
console.log("loaded", await state());
await page.evaluate(() => document.querySelector('.preview-pages canvas[data-page="4"]').scrollIntoView({ block: "center" }));
await page.waitForTimeout(600);
console.log("scrolled", await state());
await page.locator(".record-row", { hasText: "The event" }).click();
await page.locator(".cm-line", { hasText: "For Badiou the event" }).first().click();
await page.keyboard.press("End");
await page.keyboard.type(" (as a matter of ontology)", { delay: 20 });
await page.waitForTimeout(2500);
console.log("edited", await state());
await browser.close();
